a=input("Enter the value1:-  ")
b=input("Enter the value2:-  ")
print(a)
print(b)
print(a+b)
a=int(input("Enter the value1:-  "))
b=int(input("Enter the value2:-  "))
print(a+b)
float
a=float(input("Enter the value1:-  "))
b=float(input("Enter the value2:-  "))
print(a+b)
#eval
a=eval(input("Enter the value1:-  "))
b=eval(input("Enter the value2:-  "))
print(a+b)